name: GitHub-3D-Contrib

on:
  schedule:
    - cron: "0 0 * * *"   # Atualiza todo dia à meia-noite
  workflow_dispatch:      # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D Contribution
    steps:
      - uses: actions/checkout@v2
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        with:
          username: lipehsz05
      - name: Commit & Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add -A .
          git commit -m "generated"
          git push
