name: Push Changes

on:
  push:
    branches: [ main ]

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false  # importante
      - name: Make Changes
        run: |
          echo "Alguma mudança" >> file.txt
          git add file.txt
          git commit -m "Update file.txt"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: master
