name: Generate Snake Animation

on:
  schedule:
    - cron: "0 */12 * * *"  # Atualiza a cada 12h
  workflow_dispatch:        # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: lipehsz
          outputs: dist/github-contribution-grid-snake.svg

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
